name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build each folder with Cargo.toml
      run: |
        find . -type f -name 'Cargo.toml' -exec dirname {} \; | while read -r dir; do
          pushd "$dir"
          cargo build
          cargo test          
          popd
        done
