name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache tarpaulin install
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-tarpaulin
        run: |
          if [ ! -f $HOME/.cargo/bin/cargo-tarpaulin ]; then
            cargo install cargo-tarpaulin
          else
            echo "cargo-tarpaulin was cached"
          fi

      - name: Build each folder with Cargo.toml
        run: |
          for dir in $(find . -type f -name 'Cargo.toml' -exec dirname {} \; | sort -u); do
            echo "Processing $dir"
            pushd "$dir"
            cargo build
            cargo test
            cargo tarpaulin --out Xml || true
            cargo clean
            popd
          done

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          verbose: true
          fail_ci_if_error: true
          files: "**/cobertura.xml"
